### ISSUE TITLE
Cinnamon config

### ISSUE THREAD

**Issue by spsf64** [laurent85v/archuseriso#1]
Hi, thanks for this great project!
Can you create a config for cinnamon DE + lightdm?
TIA

**Comment by laurent85v** [comment]
Hi, thanks for your support. I uploaded a new config to the testing branch.
You can try it out:

    git clone --branch testing https://github.com/laurent85v/archuseriso.git
    sudo archuseriso/configs/cinnamon/build.sh

The "-l \<lang\>" build option to change the default language is also supported.

**Comment by spsf64** [comment]
Ok! I will try this weekend and report back.
Thank you for replying!

**Comment by spsf64** [comment]
Hi, just tried and got this error:

`[mkarchiso] INFO: Configuration settings
[mkarchiso] INFO:                   Command:   run
[mkarchiso] INFO:              Architecture:   x86_64
[mkarchiso] INFO:         Working directory:   work/x86_64
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:               Run command:   /root/customize_airootfs-cinnamon.sh

==> WARNING: work/x86_64/airootfs is not a mountpoint. This may have undesirable side effects.
Generating locales...
  en_US.UTF-8... done
Generation complete.
Created symlink /etc/systemd/system/multi-user.target.wants/pacman-init.service -> /etc/systemd/system/pacman-init.service.
Created symlink /etc/systemd/system/multi-user.target.wants/choose-mirror.service -> /etc/systemd/system/choose-mirror.service.
Created symlink /etc/systemd/system/default.target -> /usr/lib/systemd/system/multi-user.target.
Adding user live to group autologin
rm: cannot remove 'work/x86_64/airootfs/root/.cache/': No such file or directory
`

**Comment by laurent85v** [comment]
I could not reproduce the issue, anyway now we check file exists before removing. Fix uploaded to the testing branch. Can you retry building ? Thanks.

Commit "airootfs cleanup check file exists before removing" 8e6b6125a5cf3fc1fa98480b595c9bb3c877c686

**Comment by spsf64** [comment]
Sorry for this late reply, I am away from home for the next 10 days.
No access to linux/arch computer to test it.
I will report back as soon as I can...
