### ISSUE TITLE
aui-mkinstall/aui-mkusb fails for devices with first sector other than 2048

### ISSUE THREAD

**Issue by simontretter** [laurent85v/archuseriso#15]
Hardcoding the 1st sector in aui-mkinstall to 2048 makes the script fail with devices that start elsewhere (like Samsung T5 or T7 SSDs).

**Comment by simontretter** [comment]
Same for aui-mkusb (lines 313, 321, 329).

**Comment by laurent85v** [comment]
Currently archuseriso only supports 512 bytes logical sector size devices.

**Comment by simontretter** [comment]
Yes, and that's ok. But it does not support drives with a start sector other than 2048 (4x512), even if sector size is 512 bytes. This becomes an issue with some external drives / drive adapters (like Samsung, Jmicron).

[https://linux-blog.anracom.com/2018/12/03/linux-ssd-partition-alignment-problems-with-external-usb-to-sata-controllers-i/](url)

**Comment by laurent85v** [comment]
Release v0.6 should address the issue, give it a try.
