### ISSUE TITLE
aui-mkinstall won't boot

### ISSUE THREAD

**Issue by simontretter** [laurent85v/archuseriso#16]
For me, an iso created with aui-mkinstall won't boot, while the same iso will with aui-mkusb.

Does aui-mkinstall not support legacy bios boot? Or are there other know differences / issues?

Not sure if this is the cause, but the script fails to unmount directories. these are the last lines:

> [aui-mkinstall] INFO: Copying data to /home/user/auiwork/usb, may take some time
[aui-mkinstall] INFO: Removing live settings
[aui-mkinstall] INFO: Initialising pacman keys
[aui-mkinstall] INFO: Configuring user archie
umount: /home/user/auiwork/usb/tmp: target is busy.
umount: /home/user/auiwork/usb/run: target is busy.
umount: /home/user/auiwork/usb/dev/shm: target is busy.
umount: /home/user/auiwork/usb/dev/pts: target is busy.
umount: /home/user/auiwork/usb/dev: target is busy.
umount: /home/user/auiwork/usb/sys: target is busy.
umount: /home/user/auiwork/usb/proc: target is busy.
[aui-mkinstall] INFO: initramfs update

**Comment by laurent85v** [comment]
Both legacy bios and uefi boot are supported.

This issue might be related to the automount feature for usb devices, try to disable this feature in the file manager.

**Comment by simontretter** [comment]
That's exactly it. Thanks!
