### ISSUE TITLE
Encryption not working

### ISSUE THREAD

**Issue by antuanix** [laurent85v/archuseriso#19]
Thank you for such great tool, one thing I've noticed

aui-mkusb will create the bootable USB drive successfully but when the persistence option is chose it won't ask for a password and the boot process will interrupt

Other boot options work well

**Comment by laurent85v** [comment]
I tried with two different iso images, it works.
Any error message displayed when it fails ?

**Comment by antuanix** [comment]
This is what I get:

![image](https://user-images.githubusercontent.com/139432/100763914-127bb280-33f6-11eb-8636-89fadb6eb1c3.png)

**Comment by laurent85v** [comment]
At the prompt post the output of the following commands:
```
cat /proc/cmdline
blkid
```

**Comment by antuanix** [comment]
**cat /proc/cmdline**
`initrd=\intel-ucode.img initrd=\amd-ucode.img initrd=\initramfs-linux.img archisobasedir=arch archisolabel=AUIK cow_label=AUIPERS overlay.index=0
`

**blkid**
```

/dev/sdb1: LABEL="AUIK" UUID="02369ba3-2e54-4e50-a6e2-1c4edff32671" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="cf611466-4682-0d40-85a5-dd7fdcfb57f9"
/dev/sdb2: LABEL_FATBOOT="AUIESP" LABEL="AUIESP" UUID="CFCC-C2EF" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="0df1e00b-8f22-8d46-9c2a-bac7faad9d10"
/dev/sdb3: UUID="52f1b0ea-1197-4a1d-b36e-38953a21e867" LABEL="AUICRYPT" TYPE="crypto_LUKS" PARTUUID="e95d2a74-62ab-1145-9e27-3399256e9de3"

```

**Comment by laurent85v** [comment]
Did you run the command `cat /proc/cmdline` from the prompt right after the failed boot process ? Output doesn't seem right.

**Comment by antuanix** [comment]
Correct, I echoed the output to a file in the boot partition to be able to paste it here afterwards

There are more drives not listed here, they have LUKS partitions as well, could that be the cause of the problem?

**Comment by laurent85v** [comment]
No.
The kernel parameter for unlocking the persistent partition is missing. Kernel parameter looks like :
`cryptdevice=UUID=a1234567-b234-c345-d567-e123456789ab:auicrypt`

**Comment by antuanix** [comment]
OK thank you
Where would I add that?
What part of the code is in charge for creating that line? I could investigate it

**Comment by laurent85v** [comment]
USB flash drive partition #2
In file `loader/entries/0aui_persistence-x86_64.conf` at line _options_.

The function from aui-mkusb:
```
_encrypt_setup () {
        echo
        _msg_info "Setting up encryption"
        mkdir "${WD}/${workdir}/"{overlay,squashfs}
        mount "${WD}/${workdir}/iso/${install_dir}/x86_64/airootfs.sfs" "${WD}/${workdir}/squashfs" -o ro
        mkdir "${WD}/${workdir}/usb3/persistent_${iso_label}/x86_64/workdir"
        mount -t overlay airootper -o lowerdir="${WD}/${workdir}/squashfs",upperdir="${WD}/${workdir}/usb3/persistent_${iso_label}/x86_64/upperdir",workdir="${WD}/${workdir}/usb3/persistent_${iso_label}/x86_64/workdir" "${WD}/${workdir}/overlay"
        mount "${WD}/${workdir}/usb2" "${WD}/${workdir}/overlay/boot" -o bind
        sed -i "s|block|& encrypt|" "${WD}/${workdir}/overlay/etc/mkinitcpio.conf"
        _msg_info "initramfs update"
        arch-chroot "${WD}/${workdir}/overlay" mkinitcpio -P &> /dev/null
        sed -i "s|Storage$|& Encrypted|
                s|overlay|cryptdevice=UUID=${cryptuuid}:auicrypt &|" \
                "${WD}/${workdir}/overlay/boot/loader/entries/0aui_persistence-x86_64.conf"
        sed -i "s|Storage$|& Encrypted|
                s|overlay|cryptdevice=UUID=${cryptuuid}:auicrypt &|" \
                "${WD}/${workdir}/overlay/boot/${install_dir}/boot/syslinux/archiso_sys.cfg"
        umount "${WD}/${workdir}/overlay/boot" "${WD}/${workdir}/overlay" "/${WD}/${workdir}/squashfs"
        sleep 1
        rmdir "${WD}/${workdir}/overlay" "/${WD}/${workdir}/squashfs"
}
```
More precisely here:
```
sed -i "s|Storage$|& Encrypted|
                s|overlay|cryptdevice=UUID=${cryptuuid}:auicrypt &|" \
                "${WD}/${workdir}/overlay/boot/loader/entries/0aui_persistence-x86_64.conf"
```

**Comment by antuanix** [comment]
Thank you, manually adding the parameter worked

One of the times I tried the parameter was added correctly, the rest of times it wasn't

There are other LUKS and ZFS volumes in the computer where it's created, that could be the cause

As far as I see this issue could be closed

**Comment by laurent85v** [comment]
I see no reason regarding ZFS volumes or LUKS.

For the failed attempts did you see the info messages ?
```
[aui-mkusb] INFO: Setting up encryption
[aui-mkusb] INFO: initramfs update
```

**Comment by antuanix** [comment]
All good on that end:

[aui-mkusb] INFO: Mounting iso
[aui-mkusb] INFO: mountpoint: /home/user/aui/auiwork/iso

[aui-mkusb] INFO: Creating partitions: new gpt label
[aui-mkusb] INFO: partition #1, live partition:  5000 MiB
[aui-mkusb] INFO: partition #2, boot partition: 512 MiB
[aui-mkusb] INFO: partition #3, persistent partition: free space

[aui-mkusb] INFO: Formatting partitions
[aui-mkusb] INFO: partition #1: type Ext4, label AUIK
[aui-mkusb] INFO: partition #2: type FAT, label AUIESP

[aui-mkusb] INFO: Setting up encrypted partition, type in a passphrase of your choice

[aui-mkusb] INFO: LUKS encryption setup done! type in your passphrase to unlock partition

[aui-mkusb] INFO: partition #3: type Ext4, label AUIPERS

[aui-mkusb] INFO: Mounting partitions
[aui-mkusb] INFO: device: /dev/sdb1, mountpoint: /home/user/aui/auiwork/usb1
[aui-mkusb] INFO: device: /dev/sdb2, mountpoint: /home/user/aui/auiwork/usb2
[aui-mkusb] INFO: device: /dev/mapper/auicrypt, mountpoint: /home/user/aui/auiwork/usb3

[aui-mkusb] INFO: Copying iso data to /home/user/aui/auiwork/usb1

[aui-mkusb] INFO: Setting up persistence
[aui-mkusb] INFO: copying boot loader data to /home/user/aui/auiwork/usb2
[aui-mkusb] INFO: copying persistence data to /home/user/aui/auiwork/usb3

[aui-mkusb] INFO: Setting up encryption
[aui-mkusb] INFO: initramfs update
