### ISSUE TITLE
Xfce config

### ISSUE THREAD

**Issue by baerbock** [laurent85v/archuseriso#2]
Please add a Xfce config.

**Comment by laurent85v** [comment]
I uploaded a Xfce config to the testing branch. To try it out:

    git clone --branch testing https://github.com/laurent85v/archuseriso.git
    sudo archuseriso/configs/xfce/build.sh

Help message:
    sudo archuseriso/configs/xfce/build.sh -h

**Comment by baerbock** [comment]
Thank you very much. Sadly I'm on vacations without broadband internet so I can't test this currently.
