### ISSUE TITLE
Problem with rEFInd boot up process

### ISSUE THREAD

**Issue by antuanix** [laurent85v/archuseriso#21]
Trying to boot a very cheap laptop with a probably not so good BIOS gives this screen:

![image](https://user-images.githubusercontent.com/139432/100764704-edd40a80-33f6-11eb-9e59-2806db477c92.png)

Booting the ISO image with virt-manager (QEMU) produces the same outcome

It doesn't respond to key commands, must reset

**Comment by laurent85v** [comment]
It's a upstream issue with rEFInd
https://sourceforge.net/p/refind/code/merge-requests/30/

**Comment by antuanix** [comment]
Good to know

Thank you!

**Comment by antuanix** [comment]
Until the issue is fixed upstream the problem can easily be worked around by adding this to AUIESP/EFI/BOOT/refind.conf :

hideui banner

**Comment by laurent85v** [comment]
Release v0.6 includes the work around.

**Comment by Midou36O** [comment]
Does the provided isos include the workaround? Because i still have this issue while booting from ventoy UEFI with secure boot.
