### ISSUE TITLE
xorriso failures

### ISSUE THREAD

**Issue by ato2** [laurent85v/archuseriso#22]
i3 and console builds are OK but for mate:
  xorriso : FAILURE : Image size 928731s exceeds free space on media 478180s
or lxqt:
  xorriso : FAILURE : Image size 864139s exceeds free space on media 759632s
Details:
[aui-iso-ERR.txt](https://github.com/laurent85v/archuseriso/files/5973089/aui-iso-ERR.txt)

**Comment by laurent85v** [comment]
Building the iso in _/tmp_. The _tmpfs_ file system ran out of free space, you need more ram for doing this.

**Comment by ato2** [comment]
OK - thankx !
I assumed that 2,4G free before iso generation of 1.7G  should be OK  (I am working on 16G disk-less)
especially because xfce generation was OK and it is of similar size.
