### ISSUE TITLE
make aui-build_zfs_packages environment independent

### ISSUE THREAD

**Issue by ato2** [laurent85v/archuseriso#23]
With PKGDEST= &  BUILDDIR= in host /etc/makepkg.conf  build can fail.
Please respect host /etc/makepkg.conf  [or use private but with MAKEFLAGS="-j$(nproc)" ]
With the following patch works OK:
[patch-aui-build_zfs_packages.txt](https://github.com/laurent85v/archuseriso/files/5970935/patch-aui-build_zfs_packages.txt)

**Comment by laurent85v** [comment]
Thanks for reporting. Try this patch:

        diff --git a/archuseriso/aui-build_zfs_packages b/archuseriso/aui-build_zfs_packages
    index 589e72b..d6facbb 100755
        --- a/archuseriso/aui-build_zfs_packages
        +++ b/archuseriso/aui-build_zfs_packages
        @@ -131,12 +131,18 @@ _build_zfs_packages () {
                 sudo --user "${SCRIPTUSER}" makepkg --geninteg >> PKGBUILD
             sudo --user "${SCRIPTUSER}" updpkgsums
             cd "${auiwork}/zfsonlinux/zfs-utils/"
    -        LC_ALL=C sudo --user "${SCRIPTUSER}" \
    -        makechrootpkg -r "${ar64}" -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
    +        LC_ALL=C \
    +          sudo --user "${SCRIPTUSER}" \
    +          makechrootpkg -r "${ar64}" -- \
    +          SRCDEST="" SRCPKGDEST="" PKGDEST="" LOGDEST="" PACKAGER="" \
    +          --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
             mapfile -t zfspackages < <(find -- "${auiwork}/zfsonlinux/" | grep -e '\.pkg\.tar\.zst$' -e '\.pkg\.tar\.xz$')
             cd -- "${auiwork}/zfsonlinux/zfs-linux/"
    -        LC_ALL=C sudo --user "${SCRIPTUSER}" \
    -        makechrootpkg -r "${ar64}" -I "${zfspackages[0]}" -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
    +        LC_ALL=C \
    +          sudo --user "${SCRIPTUSER}" \
    +          makechrootpkg -r "${ar64}" -I "${zfspackages[0]}" -- \
    +          SRCDEST="" SRCPKGDEST="" PKGDEST="" LOGDEST="" PACKAGER="" \
    +          --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
             mapfile -t zfspackages < <(find -- "${auiwork}/zfsonlinux/" | grep -e '\.pkg\.tar\.zst$' -e '\.pkg\.tar\.xz$')
             cp -- "${zfspackages[@]}" "${WD}/out"
             rm -r -- "${auiwork}"

**Comment by ato2** [comment]
It's OK, but I prefer my variant - packages immediately land where I want them.
Menacing with out is not necessary - it is the whole purpose of makepkg.conf I assume.
What about semi-cosmetic grep -E ? - it is shorter and more readable.

**Comment by laurent85v** [comment]
Good point. This patch should address the issue better:

    diff --git a/archuseriso/aui-build_zfs_packages b/archuseriso/aui-build_zfs_packages
    index 589e72b..fc9f7ac 100755
    --- a/archuseriso/aui-build_zfs_packages
    +++ b/archuseriso/aui-build_zfs_packages
    @@ -19,6 +19,7 @@ help="no"
     linuxtesting="no"
     linuxversion=""
     modulesversion=""
    +pkgdest=""
     SCRIPTUSER="${SUDO_USER:-}"
     zfsversion=""
     # https://openzfs.github.io/openzfs-docs/Project%20and%20Community/Signing%20Keys.html
    @@ -63,9 +64,18 @@ _init () {
             if ! pacman -Q pacman-contrib &> /dev/null; then
                     echo 'pacman-contrib package not installed, aborting!'
                     exit 0
    +        else
    +                # check host PKGDEST setting in /etc/makepkg.conf
    +                # where packages created have to be placed
    +                if [[ -f /etc/makepkg.conf ]]; then
    +                        pkgdest=$(grep '^PKGDEST=' /etc/makepkg.conf | sed 's/PKGDEST=//')
    +                fi
    +        fi
    +        if [[ -z "${pkgdest}" ]]; then
    +                pkgdest="${WD}/out"
             fi
             mkdir -p -- "${ar64}"
    -        mkdir -p -- "${WD}/out"
    +        sudo --user "${SCRIPTUSER}" mkdir -p -- "${pkgdest}"
             mapfile -t zfssources < <(curl --silent --retry 3 --retry-connrefused --fail -- \
                        https://api.github.com/repos/openzfs/zfs/releases/latest | \
                        grep browser_download_url | cut -d':' -f2- | sed 's/\"//g; s/^[[:blank:]]*//')
    @@ -131,14 +141,20 @@ _build_zfs_packages () {
             sudo --user "${SCRIPTUSER}" makepkg --geninteg >> PKGBUILD
             sudo --user "${SCRIPTUSER}" updpkgsums
             cd "${auiwork}/zfsonlinux/zfs-utils/"
    -        LC_ALL=C sudo --user "${SCRIPTUSER}" \
    -        makechrootpkg -r "${ar64}" -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
    -        mapfile -t zfspackages < <(find -- "${auiwork}/zfsonlinux/" | grep -e '\.pkg\.tar\.zst$' -e '\.pkg\.tar\.xz$')
    +        LC_ALL=C \
    +          sudo --user "${SCRIPTUSER}" \
    +          makechrootpkg -r "${ar64}" -- \
    +          PKGDEST="" \
    +          --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
    +        mapfile -t zfspackages < <(find -- "${auiwork}/zfsonlinux/" | grep -E '\.pkg\.tar\.(zst|xz)$')
             cd -- "${auiwork}/zfsonlinux/zfs-linux/"
    -        LC_ALL=C sudo --user "${SCRIPTUSER}" \
    -        makechrootpkg -r "${ar64}" -I "${zfspackages[0]}" -- --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
    -        mapfile -t zfspackages < <(find -- "${auiwork}/zfsonlinux/" | grep -e '\.pkg\.tar\.zst$' -e '\.pkg\.tar\.xz$')
    -        cp -- "${zfspackages[@]}" "${WD}/out"
    +        LC_ALL=C \
    +          sudo --user "${SCRIPTUSER}" \
    +          makechrootpkg -r "${ar64}" -I "${zfspackages[0]}" -- \
    +          PKGDEST="" \
    +          --cleanbuild --clean --force --syncdeps --needed --noconfirm --noprogressbar
    +        mapfile -t zfspackages < <(find -- "${auiwork}/zfsonlinux/" | grep -E '\.pkg\.tar\.(zst|xz)$')
    +        sudo --user "${SCRIPTUSER}" cp -- "${zfspackages[@]}" "${pkgdest}"
             rm -r -- "${auiwork}"
     }
     
    @@ -205,9 +221,10 @@ _build_zfs_packages
     cd "${WD}"
     
     echo 'Done!'
    -echo 'ZFS packaged stored in directory '\''out'
     echo
    -find "${WD}/out" -type f -name "*.pkg.tar.*"
    +echo "${zfspackages[*]}" | sed 's|\s|\n|g' | sed 's|.*/||'
    +echo
    +echo 'ZFS packages placed in directory '\'"${pkgdest}"\'
     echo
     
     # vim: set expandtab:

**Comment by ato2** [comment]
Seems OK.  My only remarks are to programing style - my 2 lines:
      eval $(grep -s '^pkgdest=' /etc/makepkg.conf)
      pkgdest=${pkgdest:-$WD/out}
are more readable, and optimal  (sed)  then exactly same function:
      if [[ -f /etc/makepkg.conf ]]; then
         pkgdest=$(grep '^PKGDEST=' /etc/makepkg.conf | sed 's/PKGDEST=//')
      fi
      if [[ -z "${pkgdest}" ]]; then
              pkgdest="${WD}/out"
      fi
I really belive in "as few lines and chars as possible" mantra. 
2 lines 76 chars against 6 lines and 162 chars.
Parsing takes brain time - every char and line meters. Scrolling is not good (empty echo commands).
You should also try to brake long lines, and ... switch to sh (simpler, more readable, faster).
Anyway thanks for your work!

**Comment by laurent85v** [comment]
commit 405a89ae uploaded to the testing branch

Thanks for your feedback.
