### ISSUE TITLE
Thank you for this script

### ISSUE THREAD

**Issue by Archangel-Live** [laurent85v/archuseriso#25]
This is a fantastic script. I was looking for years to find an Arch Live tool resembling Remastersys. This is it. I was able to build a Live CD with an i3 profile including a modified version of the nnn file manager. I also included some plugins I wrote for nnn. All worked flawlessly. It's possible to get a completely customized live Arch system on USB. And it's lightning fast. Much faster than a regular installation of Arch on USB stick. Thank you for this. 

I had to uncomment the xf86-video-intel driver in the package list, however. My acer emachines netbook wouldn't start lightdm without the driver.

**Comment by laurent85v** [comment]
Thanks for the feedback, very much appreciated.
