### ISSUE TITLE
Disable rEFInd option?

### ISSUE THREAD

**Issue by czee** [laurent85v/archuseriso#26]
Is there a way to disable rEFInd or the EFI partition creation? Sometimes we run a headless system and the motherboard BIOS defaults to this partition boot order first. Then you need to connect keyboard, graphics card and screen to set the BIOS properly.

**Comment by laurent85v** [comment]
To disable uefi booting your can rename the EFI directory of the efi partition to something else. 
To keep uefi booting and bypass rEFInd rename the following directories and file this way: 

    cd EFI
    mv BOOT refind
    mv live BOOT
    mv BOOT/livedisk.efi BOOT/BOOTx64.efi

**Comment by laurent85v** [comment]
Coming in next release a new `--no-refind` option for creating usb drives. https://github.com/laurent85v/archuseriso/commit/fd4de8185b7eddd88ddecd1178fc3bad16af4d3e

**Comment by czee** [comment]
Cool thanks

**Comment by laurent85v** [comment]
Version 0.6.4 released, closing.

**Comment by czee** [comment]
I got this error on the latest package:

[aui-mkhybrid] INFO: mountpoint: /home/user/.tmp/tmp.TJMgHFnWyv/auiwork.to7cJLjz/iso
Error: /home/user/.tmp/tmp.TJMgHFnWyv/out/aui-xfce-linux_5_11_15-0422-x64.iso is not a compatible iso image!

**Comment by laurent85v** [comment]
Versions released with new features may require a newly generated iso image. Check archuseriso is updated to the latest version v0.6.4.1 and use a newly generated iso image for creating the usb drive. Or download an iso image from http://dl.gnutux.fr/archuseriso, these iso images are compatible with the latest version.

**Comment by laurent85v** [comment]
Versions released with new features may require a newly generated iso image. Check archuseriso is updated to the latest version v0.6.4.1 and use a newly generated iso image for creating the usb drive. Or download an iso image from http://dl.gnutux.fr/archuseriso, these iso images are compatible with the latest version.

**Comment by laurent85v** [comment]
New features also affects profile definition. Rebase your profile on the latest profile released.

**Comment by czee** [comment]
Ok thanks, I'll try that.
