### ISSUE TITLE
Startup script (script= form cmdline) needs ^D to start

### ISSUE THREAD

**Issue by ato2** [laurent85v/archuseriso#27]
I am using "script=..." cmdline boot option on my disk-less machines to auto-configure them after PXE boot.
I am using aui-console (latest aui-console-linux_5_11_15-0417-x64.iso)
Now it is necessary to provide ^D or logout on console, after which script executes as before.
So it seems that /root/.zlogin is not executed automatically for root on console as it was before.

**Comment by laurent85v** [comment]
I made a test with the same iso and using the _script=_ kernel parameter to download a basic bash script and it works, the script executes without issue!

**Comment by ato2** [comment]
It was mistake in my startup script :(
