### ISSUE TITLE
gets struck on installing packages

### ISSUE THREAD

**Issue by MohammadHisham** [laurent85v/archuseriso#30]
when i execute aui-mkiso kde then it gets struck on installing packages

**Comment by laurent85v** [comment]
Use the _--verbose_ option to get more info:
`sudo aui-mkiso --verbose kde`

**Comment by MohammadHisham** [comment]
i will try

**Comment by MohammadHisham** [comment]
i am unable to remove the work directory

**Comment by MohammadHisham** [comment]
![1](https://user-images.githubusercontent.com/74092485/118763015-c71a6b00-b894-11eb-9c5a-e6e2a99f21f7.PNG)

**Comment by laurent85v** [comment]
Issue not related to archuseriso. See the links below, might help:
https://wiki.archlinux.org/title/Pacman/Package_signing#Troubleshooting
https://bbs.archlinux.org/viewtopic.php?id=253809
