### ISSUE TITLE
Question: How do I change the default boot option in UEFI mode

### ISSUE THREAD

**Issue by Archangel-Live** [laurent85v/archuseriso#32]
Excellent project. Very useful!!!

I have a question: The default boot option is "persistance".
I found out myself how to change this in BIOS mode.

But I don't understand how to change it in UEFI mode. 

I'd like to make booting "live to ram" the default.
Please point out which files I have to edit to achieve this. 

I'm using the i3 profile.

**Comment by laurent85v** [comment]
Thanks for your support.

ESP partition, edit file _/loader/loader.conf_ and change default to:
`default archiso_3_ram-x86_64-linux.conf`

**Comment by Archangel-Live** [comment]
Did not succeed yet. I edited 
archuseriso/profiles/i3/efiboot/loader/loader.conf

but the boot menu which opens after the UEFI splash screen is the same, the first entry being "persistence", highlighted and still booting :-(

**Comment by laurent85v** [comment]
Both work for me, either editing profile, either editing usb drive's config file.

**Comment by Archangel-Live** [comment]
I guess I'm too dumb for this. I don't even understand how this boot menu is generated. 
It seems to be a combination of the entries of two directories:
i3/efiboot/loader/entries/
i3/aui/liveusb/loader/entries/

There are two corresponding loader.conf files with different default entries:

i3/efiboot/loader/loader.conf  --->  default archiso-x86_64-linux.conf
i3/aui/liveusb/loader/loader.conf  ---> default archiso-aui-0-x86_64-linux.conf

I don't understand how this works. 
Anyway, thanks for your help! 
And again: Huge thanks for the great Archuseriso project. I'm very happy to have this.

**Comment by laurent85v** [comment]
Have you tried this https://github.com/laurent85v/archuseriso/issues/32#issuecomment-863575080 ?

Regarding the profile changes, you need to edit both files _i3/efiboot/loader/loader.conf_ and _i3/aui/liveusb/loader/loader.conf_

Change the default to:
`default archiso_3_ram-x86_64-linux.conf`

_i3/efiboot/loader/loader.conf_  is the configuration file for the iso image
_i3/aui/liveusb/loader/loader.conf_ is the configuration file for the live usb created by _aui-mkusb_

**Comment by Archangel-Live** [comment]
That's it, it works :100: 
I edited both files and everything's fine. Thanks again, Laurent :+1:
