### ISSUE TITLE
Missing no refind option?

### ISSUE THREAD

**Issue by th1nhhdk** [laurent85v/archuseriso#33]
V0.6.4 says that there is a no refind option but in V0.6.8 the option does not work(or exist)?

**Comment by laurent85v** [comment]
Works as far as I know. Provide more details, iso image used, commands used, expected behavior, error messages if any.

**Comment by th1nhhdk** [comment]
Command:
sudo aui-mkiso --pkg-dir ./ViNux/kde/binpkgs --no-refind --verbose ./ViNux/kde

Its say invalid argument(some what like that)

**Comment by laurent85v** [comment]
The _"--no-refind"_ option does not apply to creating the iso image, see the command line help `aui-mkiso --help`. The _"--no-refind"_ option is available when creating the usb drive, see `aui-mkusb --help`, `aui-mkinstall --help`, `aui-mkhybrid --help`.

**Comment by th1nhhdk** [comment]
Wait...auimk-install makes an arch installer?

**Comment by laurent85v** [comment]
rEFInd is more versatile for booting broken bootloaders on the hard drive. Systemd boot is still available on next screen.

**Comment by th1nhhdk** [comment]
No, i mean is there anyway to remove rEFInd?I dont like it.

**Comment by laurent85v** [comment]
Currently from the iso image no way. Or boot the iso image in bios mode.

**Comment by th1nhhdk** [comment]
Ok
