### ISSUE TITLE
aui-mkinstall with i3 desktop iso fails with missing /etc/samba/smb.conf

### ISSUE THREAD

**Issue by tripy37** [laurent85v/archuseriso#36]
Have just been trying out this project and love it for what I was looking for.  One error I did come across and have not seen any closed issues mention this. During the aui-mkinstall it stops with the error unable to find /etc/samba/smb.conf I had a look at the aui-mkinstall script and found a [sed command](https://github.com/laurent85v/archuseriso/blob/1814fbfdbb2bf79206a155f877b8ed36202758bc/archuseriso/aui-mkinstall#L548) looking for that file in the settings username section, I then realised that samba should have been installed but the i3 profile does not have samba in the packages file.  I decided to edit the sed command and remove the reference to smb.conf file and the usb drive built fine (writing this at the moment with said usb)

Just thought I would try make you aware of that build if said sed command could possibly check if file exists and be able to carry on if doesn't exist. Or would installing samba be a requirement

**Comment by laurent85v** [comment]
Version 0.6.10 released, closing issue.
