### ISSUE TITLE
[Question] Difference between `aui-mkusb` and `aui-mkinstall`.

### ISSUE THREAD

**Issue by HarshalRathore** [laurent85v/archuseriso#37]
I have read the Readme many times and also did google to clarify any of my side misunderstandings of the two terms. 
If `aui-mkusb` is the one that creates persistent USB able to boot on both Legacy BIOS and UEFI then what is `aui-mkinstall` how is it different from `aui-mkusb`

>Permanent installation except systemd journal configured in volatile mode.

this statement **Permanent installation** is even more confusing for me.

_Note :- When I say **Persistent** I mean one which retains user-created data even after reboots. eg I make a folder named harshal and say a text file name file.txt. So with persistence, I expect the USB to retain that folder and files with their respective content in it after numerous reboots._

**Comment by laurent85v** [comment]
aui-mkinstall performs a standard installation on the usb drive.
