### ISSUE TITLE
xorriso: command not found

### ISSUE THREAD

**Issue by Dialga** [laurent85v/archuseriso#39]
```
[aui-mkiso] INFO: Done!
[aui-mkiso] INFO: Creating checksum file for self-test...
[aui-mkiso] INFO: Done!
[aui-mkiso] INFO: Creating ISO image...
/usr/local/bin/aui-mkiso: line 1342: xorriso: command not found
```
Making an iso takes ages - I only found the above error after running aui-mkiso numerous times, finally with the -v flag.
Hence can the script be enhanced to detect the absence of libisoburn earlier? Or output `xorriso: command not found` as a fatal error.

**Comment by laurent85v** [comment]
Dependencies are documented in the readme.md page / Installation.

**Comment by Dialga** [comment]
That's true and I did initially miss that in my haste but I still think such a fatal error shouldn't be hidden behind the verbose flag.
