### ISSUE TITLE
Minimizing disk access

### ISSUE THREAD

**Issue by omeringen** [laurent85v/archuseriso#4]
Thanks for the script, i am using it for a while.
I wonder if these two are necessary :

- ext4 without a journal
- systemd journal to store its journals in RAM

https://wiki.archlinux.org/index.php/Install_Arch_Linux_on_a_removable_medium#Minimizing_disk_access

Is it possible to add them to the script ?

**Comment by laurent85v** [comment]
Thanks for your feedback.

systemd journal is already configured for storing log data only in memory.
From _/etc/systemd/journald.conf_:
```
[Journal]
Storage=volatile
```
I updated _aui-mkusb_ and _aui-mkinstall_, in the coming release ext4 journal is disabled by default. User may enable it using new _--ext4journal_ option.

**Comment by laurent85v** [comment]
Version 0.4.2 released, ext4 journal now disabled by default.
