### ISSUE TITLE
Can't fetch  archuseriso-0.6.12.tar.gz from some of my IPs

### ISSUE THREAD

**Issue by ato2** [laurent85v/archuseriso#40]
Please unblock 194.29.146.22 on Your firewall:
yay -Sy archuseriso --noconfirm --needed
==> Retrieving sources...
 -> Downloading archuseriso-0.6.12.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0
curl: (28) Failed to connect to dl.gnutux.fr port 80 after 129537 ms: Connection timed out
Warning: Problem : timeout. Will retry in 3 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:26 --:--:--     0

Same by hand:

% curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o archuseriso-0.6.12.tar.gz.part http://dl.gnutux.fr/sources/archuseriso/archuseriso-0.6.12.tar.gz                 [1]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0^C

I can fetch it from other hosts:

curl -fLRO http://dl.gnutux.fr/sources/archuseriso/archuseriso-0.6.12.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1661k  100 1661k    0     0  4620k      0 --:--:-- --:--:-- --:--:-- 4628k

**Comment by laurent85v** [comment]
Check your side, high load on the server side may result in ip ban for unsolicited traffic from an ip address.
