### ISSUE TITLE
no error message if --add-pkg package does not exist

### ISSUE THREAD

**Issue by eulenleber** [laurent85v/archuseriso#44]
silently fails without notice due to https://github.com/laurent85v/archuseriso/blob/master/archuseriso/aui-mkiso#L485

**Comment by laurent85v** [comment]
Thanks for reporting issue. Upcoming release should address the issue.

commit https://github.com/laurent85v/archuseriso/commit/a0504b0271dd41455b967438f87d2d2f9cf5d7b0
