### ISSUE TITLE
Startup script not always fetched  in  /root/.automated_script.sh

### ISSUE THREAD

**Issue by ato2** [laurent85v/archuseriso#46]
I am net-booting a lot of disk-less computers in student labs with script=url cmdline parameter
There is non-deterministic behavior, especially on computers with a lot of network interfaces.
Probably some kind of network setup delay.
Adding  --retry 5 --retry-delay 1 --retry-all-errors  to curl options solves problem.

**Comment by laurent85v** [comment]
A bug report is open for Archiso about this, can you test the suggested patch instead?

https://gitlab.archlinux.org/archlinux/archiso/-/merge_requests/235/diffs?commit_id=f60525103d152923e1321490936cf17fd033bf4d

**Comment by laurent85v** [comment]
Fix released https://github.com/laurent85v/archuseriso/commit/82413b300076197b52e99fddccaedfbe202ce6dc
