### ISSUE TITLE
Error when trying to mkusb

### ISSUE THREAD

**Issue by dcihon** [laurent85v/archuseriso#47]
`[demo@Manjaro archuseriso]$ sudo ./aui-mkusb aui-xfce-linux_6_1_11-0213-x64.iso /dev/sda

[aui-mkusb] INFO: ISO file:   aui-xfce-linux_6_1_11-0213-x64.iso
[aui-mkusb] INFO: USB device: /dev/sda

Confirm write to ProductCode  7.5G (N/y)? y

[aui-mkusb] INFO: Mount iso
[aui-mkusb] INFO: mountpoint: /home/demo/Downloads/isos/archuseriso/archuseriso/auiwork.cZw4fXxU/iso
Error: v7 gen iso image, gen version mismatch. aui-mkusb requires gen v9!

aui-mkusb: make a bootable usb drive with persistence.

Synopsis:
aui-mkusb [options] <archuseriso iso image> <usb device>

Help:
aui-mkusb --help`

**Comment by dcihon** [comment]
I just changed v9 to v7 in the script and it worked.

**Comment by dcihon** [comment]
I successfully was able to get 1 persistent usb created from one of the xfce iso's.
Now trying to do another iso. I keep getting ran out of space messages.
I am using a 8GB usb drive.

**Comment by laurent85v** [comment]
> I just changed v9 to v7 in the script and it worked.

The iso images and the version of archuseriso are linked together, you may have side effects or unknown bugs if you bypass this check.

**Comment by laurent85v** [comment]
> [aui-mkusb] INFO: Copy live image to /home/demo/Downloads/isos/archuseriso/archuseriso/auiwork.A0XMLpxB/usbro cp: error writing '/home/demo/Downloads/isos/archuseriso/archuseriso/auiwork.A0XMLpxB/usbro/arch/x86_64/airootfs.sfs': No space left on device

The size of the first partition is too small. The size calculation will be fixed in the next release.
In the meantime, you can modify the code of aui-mkusb:

    diff --git a/archuseriso/aui-mkusb b/archuseriso/aui-mkusb
    index a0a8d20..e846c09 100755
    --- a/archuseriso/aui-mkusb
    +++ b/archuseriso/aui-mkusb
    @@ -397,7 +397,7 @@ _usb_prepare() {
         fi
 
         if [[ -f "${WD}/${workdir}/iso/${install_dir}/${arch}/airootfs.sfs" ]]; then
    -        iso_size=$(( $(du -bs "${WD}/${workdir}/iso/${install_dir}/${arch}" | awk '{print $1}') / 1048576 * 106 / 100 ))
    +        iso_size=$(( $(du -bs "${WD}/${workdir}/iso/${install_dir}/${arch}" | awk '{print $1}') / 1048576 * 1065 / 1000 ))
             copytoram_size=$(( $(stat -c %s "${WD}/${workdir}/iso/${install_dir}/${arch}/airootfs.sfs") + 1024 * 64 ))
         fi

**Comment by laurent85v** [comment]
Fix released https://github.com/laurent85v/archuseriso/commit/d55cf5e5819589609097b7d4775a9580d43410b5
