### ISSUE TITLE
erroneous i3 profile

### ISSUE THREAD

**Issue by Merlin-Brandt** [laurent85v/archuseriso#48]
I ran following commands from inside an archuseriso-livesystem[1]:

`# aui-mkiso i3 --add-pkg=dos2unix --verbose`
`# aui-mkusb out/aui-i3-linux_6_4_10-0812-x64.iso /dev/sdX`,

however the resulting fresh installation is unusable after successfully booting into it,

since all users have an empty password, but the lightdm configuration does not allow logging in with an empty password.

---
[1] dl.gnutux.fr/archuseriso/iso/aui-console-linux_6_4_9-0810-x64.iso

**Comment by laurent85v** [comment]
I was unable to reproduce the problem. Additional information is needed on the problem encountered.

For your information the autologin is active, at startup there is no login manager, the system boots directly into i3. In addition lightdm allows you to connect without entering a password by simply pressing the enter key for accounts that do not have a password as is the case for the live user.

If this is not the behavior you are getting then an error has occurred at some point. You may check logs for any error messages.
