### ISSUE TITLE
The addition of the --force-removable option to enable the bypassing of USB being misidentified as a block device.

### ISSUE THREAD

**Issue by ZhymabekRoman** [laurent85v/archuseriso#50]
I use Arch Linux and have Kingston DataTraveler 64 GB. I wanted to install Arch with persistence using archuseriso toolkits and occurred this problem:

```bash
$ sudo aui-mkusb --size-esp=1G --size-cow=40G --rootfs=f2fs aui-lxqt-linux_6_6_1-1109-x64.iso /dev/sdh
Error: /dev/sdh is not a removable block device!
```

I tried to manually check device using lsblk as in code:
```bash
$ lsblk -dnro hotplug -- /dev/sdh
0
```

```bash
$ udisksctl status
MODEL                     REVISION  SERIAL               DEVICE
--------------------------------------------------------------------------
...
Kingston DataTraveler 3.0 0000      E0D55E6C09F91770892C0333 sdh
```

Very strange behavior, probably bug in lsblk (?). So I just commented this check in archuseriso code and seems all works fine.

Huge thanks for your work!

**Comment by ZhymabekRoman** [comment]
I found option "Mass USB storage emulation type" in my BIOS. I think that is the problem. And unfortunately in my 2008 year setup USB doesn't want to boot :/ In my notebooks all ok

**Comment by ZhymabekRoman** [comment]
I also tested in non UEFI PC - same problem

**Comment by laurent85v** [comment]
Thank you for your support.
lsblk provides two different options for checking the removable status of a device. Can you check the result of :
`$ lsblk -dnro rm -- /dev/sdh`

**Comment by ZhymabekRoman** [comment]
```bash
roman@roman ~> lsblk -dnro hotplug -- /dev/sdh
0
roman@roman ~> lsblk -dnro rm -- /dev/sdh
1

```

**Comment by laurent85v** [comment]
Changing the lsblk command option to 'rm' should be enough to resolve the issue.
commit https://github.com/laurent85v/archuseriso/commit/fdf490550038dcee2dc69d6ba87efa195f8edadc
Version  0.7.14 released

**Comment by ZhymabekRoman** [comment]
Thanks! I will open a different issue for booting problem
