### ISSUE TITLE
council between aui-mkusb and aui-mkinstall

### ISSUE THREAD

**Issue by bsd276** [laurent85v/archuseriso#52]
Hello,

I travel regularly and use different PCs to work that are made available to me.
The idea is to boot on these different PCs on a USB SSD disk with the encryption option in order to find my working environment, to update the applications and the system (security update, Microcode ).

I read the post below:
https://github.com/laurent85v/archuseriso/issues/37

If I understand correctly, the "live" version is a read-only image that retains the data created by the user.

What would be the best choice between aui-mkusb and aui-mkinstall knowing that the PCs will be of different models (AMD, INTEL) and that I wish to update the applications and the system (security update, Microcode )?

For the Microcode update, is it automatic with the pacman -Syyu command, or do I have to take other steps?
cat /boot/loader/entries/archiso-aui-0-x86_64-linux.conf
title Archuseriso Cinnamon (x86_64, UEFI)
sort-key 01
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /amd-ucode.img
...

Thanks

**Comment by hartmark** [comment]
Go with aui-mkinstall. Just have your system updated it will apply the needed microcode automatically when you boot it up.

**Comment by bsd276** [comment]
Thank
