### ISSUE TITLE
Missing GPL2/license.txt

### ISSUE THREAD

**Issue by tobfromme** [laurent85v/archuseriso#55]
This built previously on kernel 6.6.7 but now on 6.7.0-arch3-1, I'm getting the error below.  I'm using the same commands I used successfully on previous kernels.  Attached is the full log.
[log.txt](https://github.com/laurent85v/archuseriso/files/13972441/log.txt)

```
  -> Running build hook: [filesystems]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux.img'
==> Image generation successful
[aui-mkiso] INFO: Creating a list of installed packages on live-enviroment...
[aui-mkiso] INFO: Done!
[aui-mkiso] INFO: Setting up SYSLINUX for BIOS booting from a disk...
[aui-mkiso] INFO: Preparing kernel and initramfs for the ISO 9660 file system...
[aui-mkiso] INFO: Done!
install: cannot stat '/root/work/x86_64/airootfs/usr/share/licenses/common/GPL2/license.txt': No such file or directory
```
What I've found is the licenses have been moved to `/usr/share/licenses/spdx` in the `licenses` core package 2 days ago:

https://gitlab.archlinux.org/archlinux/packaging/packages/licenses/-/blob/3c208d6eb23e2ad9590fc168f43a0d06ab47c6d6/PKGBUILD

**Comment by laurent85v** [comment]
Fix released 
Commit 999a8d54c027c57ee862dccaee25bb96b00630fe
Release 0.7.15.3

**Comment by tobfromme** [comment]
Thanks for the quick fix.  I use the AUR, so I'll wait until that is updated to test.  Thanks again!

**Comment by laurent85v** [comment]
archuseriso update on the AUR is now available.
Thanks for reporting this bug.

**Comment by tobfromme** [comment]
Thanks for the quick turnaround!
