### ISSUE TITLE
Image with Gnome is missing gnome-control-center

### ISSUE THREAD

**Issue by DanielGibson** [laurent85v/archuseriso#58]
I'm using aui-gnome-linux_6_9_7-0629-x64.img from http://dl.gnutux.fr/archuseriso/img/ and noticed that there are no Gnome settings.
It turned out that the `gnome-control-center` package is not installed.

I think it should be installed by default, as having settings e.g. to configure the keyboard layout is pretty essential.

Thanks!

**Comment by laurent85v** [comment]
Thanks for reporting the issue.
Update released.

**Comment by DanielGibson** [comment]
Wow, that was fast, thanks! :)
I can confirm that the settings are available now.

Also thanks for creating this, I find those images are very useful to test recent versions of various desktops (with and without Wayland) without risking to mess up my installed operating systems.
