### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by tuxarch** [laurent85v/archuseriso#60]
https://dl.gnutux.fr/archuseriso/iso
https://dl.gnutux.fr/archuseriso/img

Object not found!

The requested resource was not found. The link on the page is invalid or out of date. Please notify the author of this page about the error.

If you believe this is a server error, please notify the webmaster.

**Comment by laurent85v** [comment]
The download server for archuseriso currently only supports unencrypted http protocol.
http://dl.gnutux.fr/archuseriso/iso
http://dl.gnutux.fr/archuseriso/img
