### ISSUE TITLE
The libva-vdpau-driver package referenced in the several profile package files is no longer available in AUR

### ISSUE THREAD

**Issue by ghost** [laurent85v/archuseriso#61]
Hi. I think the `libva-vdpau-driver` package referenced in the non-console profiles is no longer available in the AUR.

When I tried to create an ISO with the KDE profile, I got an error saying:
```
error: target not found: libva-vdpau-driver
```

I tried searching for the package at [https://aur.archlinux.org/packages?O=0&K=libva-vdpau-driver](https://aur.archlinux.org/packages?O=0&K=libva-vdpau-driver), and the only results were `libva-vdpau-driver-vp9-git`, `libva-vdpau-driver-wayland`, and `libva-vdpau-driver-shadow-nvidia`.

And looking at the [history for the Arch Linux Wiki page for Hardware video acceleration](https://wiki.archlinux.org/index.php?title=Hardware_video_acceleration&action=history) shows that references to `libva-vdpau-driver` was updated on November 30th because "not packaged, obsolete".

Should it be removed from the various `packages.x86_64` files? Thanks. Sorry, this is my first issue.

**Comment by tonymasexyz** [comment]
Thank you. I appreciate the project. Very easy to use.
