### ISSUE TITLE
about missing installed fonts

### ISSUE THREAD

**Issue by omeringen** [laurent85v/archuseriso#7]
Hi,
I suggest including _ttf-dejavu_ and _ttf-liberation_ fonts installed.

After creating a new USB i realized that websites look ugly. Firefox prefers some other font for default because _ttf-dejavu_ and _ttf-liberation_ aren't installed. I didn't check other programs one by one. After getting these fonts via pacman, everything looks nice again.

/etc/fonts/conf.avail/60-latin.conf
```
<fontconfig>
  <description>Set preferable fonts for Latin</description>
        <alias>
                <family>serif</family>
                <prefer>
                        <family>DejaVu Serif</family>
                        <family>Times New Roman</family>
                        <family>Thorndale AMT</family>
                        <family>Luxi Serif</family>
                        <family>Nimbus Roman No9 L</family>
                        <family>Nimbus Roman</family>
                        <family>Times</family>
                </prefer>

```

**Comment by laurent85v** [comment]
To investigate into this issue can you provide the command used to generate the iso image and from the live desktop environment the output of the following commands:

```
fc-match serif
fc-match sans
fc-match mono
```

For the time being you may use the `--addpkg` command option this way, example generating the  _Xfce_ iso image:

`sudo aui-mkiso xfce --addpkg ttf-dejavu,ttf-liberation`

Thanks for your feedback.

**Comment by omeringen** [comment]
Last time, i directly used your _archuseriso-kde-0625-x64.iso_ file.
I used it again on my spare USB to check what you asked:

Yeah the ugly one is Noto :) After getting ttf-dejavu and ttf-liberation Firefox automatically changed the default font. Not a big deal, but it might be better to have them installed.
```
live@archiso ~ % fc-match serif
NotoSerif-Regular.ttf: "Noto Serif" "Regular"
live@archiso ~ % fc-match sans
NotoSans-Regular.ttf: "Noto Sans" "Regular"
live@archiso ~ % fc-match mono
NotoSansMono-Regular.ttf: "Noto Sans Mono" "Regular"
```

**Comment by laurent85v** [comment]
That was already the fonts used in previous releases for Kde Plasma. _noto-fonts_ is widely used as it also covers most non latin unicode characters, some are missing with ttf-dejavu.

**Comment by omeringen** [comment]
Thanks for explanation.
