### ISSUE TITLE
persistence features

### ISSUE THREAD

**Issue by omeringen** [laurent85v/archuseriso#8]
Hi,
I don't know if this kind of enhancement fits to your project or not, just wanted to ask your opinion.

MX Linux which is based on antix, has special tools and features for USB systems. For example if you choose, changes on file system are stored on RAM then these changes are transfered to the disk on shutdown via rsync. This is a useful feature about speed and USB stick life.

I like arch and i'd like to have this kind of feature.

Here is the antix explanation:
https://download.tuxfamily.org/antix/docs-antiX-19/FAQ/persistence.html
https://gitlab.com/antiX-Linux/antiX-Gfxboot/blob/master/Help/antiX/en.html#L309

**Comment by laurent85v** [comment]
Extending persistence features is not planned. Current settings are already optimized for usb sticks. Ext4 journal is disabled by default and journald is in volatile mode for minimizing writes.

**Comment by omeringen** [comment]
Thanks for the answer.
